site_name: 朱子建 Tze-Chien Chu (Frank) Notes
theme:
  name: material
nav:
  - 'Home': 'index.md'
  - '2026-05': 'Y2026/Y2026-05.md'
  - 'Books': './books/books.md'
  - 'Video Lectures': './video_lecture.md'
  - 'Pins': 'pins.md'
  - 'Pico': 'PICO_Resources.md'
  - 'Python': 'Python_Resources.md'  
  - 'Litex&FPGA': 'LitexAndFPGA.md' 
  - 'Tutorial': 'tutorial.md'
  - 'Resources': 'resources.md' 
  - 'Papers': 'papers.md'
  - 'Facts': 'facts.md'
  - 'Github Collection': 'github.md'
  - 'Templates': 'templates.md'
  - 'Quotes': './quotes.md'
  - 'Ideas': './ideas.md'
  - 'About Me': './about.md'
  #- 'Schematics': './private/schematics.md'
  - '*Magazins (Local)': './mags/index.md'
  #- '*Peoples' : './private/peoples.md'
  #- '*Projects': './private/projects.md'
  #- '*Personal': './private/personal.md'
  #- '*Source (Local)': './private/local_source.md'
  #- 'TWOT': './TWOT/twot.md'
  - 'Help' : 'Help.md'

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

theme:
  name: material
  features:
    #- navigation.tabs
    #- navigation.tabs.sticky
    #- toc.integrate
    - content.code.select
    - content.code.copy

#plugins:
#  - pdf-export

