site_name: Frank's Notes
theme:
  name: material
nav:
  - 'Help': 'index.md'
  - '2025-06': 'Y2025/Y2025-06.md'
  - '2025-05': 'Y2025/Y2025-05.md'
  - '2025': 'Y2025/Y2025.md'
  - '2024': 'Y2024.md'
  - 'Schematics': './private/schematics.md'
  - 'Pins': 'pins.md'
  - 'Tutorial': 'tutorial.md'
  - 'Resources': 'resources.md'
  - 'Papers': 'papers.md'
  - 'Facts': 'facts.md'
  - 'Github Collection': 'github.md'
  - 'Templates': 'templates.md'
  - 'Magazins (Local)': './mags/index.md'
  - 'Peoples' : './private/peoples.md'
  - 'Projects': './private/projects.md'
  - 'Quotes & Ideas': './private/qandi.md'
  - 'Personal': './private/personal.md'
  - 'Source (Local)': './private/local_source.md'

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material
  features:
    #- navigation.tabs
    - toc.integrate
    - content.code.select
    - content.code.copy

#plugins:
#  - pdf-export

