site_name: Frank's Notes
theme:
  name: material
nav:
  - 'Help': 'index.md'
  - '2025-01': 'Y2025/Y2025-01.md'
  - '2024': 'Y2024.md'
  - 'Schematics': 'schematics.md'
  - 'Pins': 'pins.md'
  - 'Tutorial': 'tutorial.md'
  - 'Resources': 'resources.md'
  - 'Papers': 'papers.md'
  - 'Facts': 'facts.md'
  - 'Projects': 'projects.md'
  - 'Templates': 'templates.md'
  - 'Quotes & Ideas': 'qandi.md'
  - 'Personal': 'personal.md'

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material
  features:
    - content.code.select
    - content.code.copy
